# Site settings
title: Fall-Back
email: andy.kirk@gridlight-design.co.uk
description: "Progressive Enhancement patterns."
baseurl: ""
url: "http://fall-back.github.io/"

# Build settings
markdown: kramdown
