# Site settings
title: "Fall-Back"
email: "andy.kirk@gridlight-design.co.uk"
description: "Accessible, Progressive Enhancement patterns."
repository: "Fall-Back/Fall-Back.github.io"
baseurl: ""
url: "http://fall-back.github.io/"
port: 4001

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      head_scripts: false
      head_stylesheets: false
      head_style: false
      body_class: false
      body_end_script: false
      load_highlighter: false


# Build settings
markdown: kramdown


kramdown:
  auto_ids:       true

# Prevent github pages creating stuff:
theme: null

exclude: [
    "_archive",
    "bower.json",
    "bower_components",
    "Gemfile",
    "Gemfile.lock",
    "gulpfile.js",
    "local-gulp.bat",
    "local-jekyll.bat",
    "node_modules",
    "package.json",
    "README.md"
]